name: Bug report
description: Report a reproducible bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction
      description: Steps and minimal sample
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Package version
      placeholder: 0.1.0
    validations:
      required: true
  - type: input
    id: runtime
    attributes:
      label: Runtime
      placeholder: Node.js 20.11.1
    validations:
      required: true
